name: flutter_country
description: Flutter Country, All Data Country
version: 1.0.0
author:
homepage:

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg:
    git:
      url: https://github.com/boanergepro/flutter_svg.git
      ref: 0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/flags/
